/**
 * Created by anchao on 2016/6/29.
 */
export const SHOWLOADING_COMMON = 'SHOWLOADING_COMMON'
export const HIDELOADING_COMMON = 'HIDELOADING_COMMON'
export const INCREASEINVOKE_COMMON = 'INCREASEINVOKE_COMMON'
export const DECREASEINVOKE_COMMON = 'DECREASEINVOKE_COMMON'
