/**
 * 功能: 数据源管理所有动作名称
 * 作者: tanglimei
 * 日期: 2020.02.04
 */

export const GET_DATASOURCE_TABLE_LIST_DATASOURCE_MANAGE = 'GET_DATASOURCE_TABLE_LIST_DATASOURCE_MANAGE'
export const SET_DATASOURCE_LIST_HEADERS_DATASOURCE_MANAGE = 'SET_DATASOURCE_LIST_HEADERS_DATASOURCE_MANAGE'
export const SET_SEARCH_VALUE_DATASOURCE_MANAGE = 'SET_SEARCH_VALUE_DATASOURCE_MANAGE'
export const SET_DATA_SOURCE_TYPE_DATASOURCE_MANAGE = 'SET_DATA_SOURCE_TYPE_DATASOURCE_MANAGE'
export const SET_CURRENT_DATASOURCE_MANAGE = 'SET_CURRENT_DATASOURCE_MANAGE'
export const GET_SYNC_CURRENT_DATA_DATASOURCE_MANAGE = 'GET_SYNC_CURRENT_DATA_DATASOURCE_MANAGE'
export const SET_SYNC_TABLES_DATASOURCE_MANAGE = 'SET_SYNC_TABLES_DATASOURCE_MANAGE'
export const CLEAR_SYNC_CURRENT_DATA_DATASOURCE_MANAGE = 'CLEAR_SYNC_CURRENT_DATA_DATASOURCE_MANAGE'

export const GET_ORIGIN_TABLE_DATASOURCE_MANAGE = 'GET_ORIGIN_TABLE_DATASOURCE_MANAGE'
export const SET_ORIGIN_TABLE_HEADERS_DATASOURCE_MANAGE = 'GET_ORIGIN_TABLE_LIST_DATASOURCE_MANAGE'
export const GET_ORIGIN_FIELD_LIST_DATASOURCE_MANAGE = 'GET_ORIGIN_FIELD_LIST_DATASOURCE_MANAGE'
export const SET_ORIGIN_FIELD_LIST_HEADERS_DATASOURCE_MANAGE = 'SET_ORIGIN_FIELD_LIST_HEADERS_DATASOURCE_MANAGE'
